### PR TITLE
add insertBefore, insertAfter properties

### PR DESCRIPTION
**Pull request by alevkon**
Sometimes it's important to place the iframe in a specific position inside a container – i.e. before or after any element. This fix implements new `insertBefore` and `insertAfter` properties so the user can control the insert position.

### CODE REVIEW

**Comment by oyvindkinsey** [comment]
This is currently already possible by simply using an empty span/div as the container, and placing that where you want the iframe. Do you think the additional complexity is worth it?

**Comment by alevkon** [comment]
Yes, there are some cases which cannot be solved like this. I am currently developing a service with public client-side API, where user can do something like this:
```
<div>First block</div>
<script>serviceAPI.insertWidget()</script>
<div>Last block</div>
```
So, if the API user wants to insert the widget exactly between first and last blocks, he has to write some additional wrapper. This is not a good decision – it's not obvious, requires some time to find the solution, requires some additional docs and makes the page bigger for no reason.

**Comment by oyvindkinsey** [comment]
> So, if the API user wants to insert my widget exactly between first and last blocks, he has to write some additional wrapper around the script

This isn't necessarily true - your script could create a span/div and insert it wherever you want, and then use that as the container. 

For your specific example, you would actually want to use `document.write` to insert the element directly after the script, and then use the element you added as the container.

**Comment by alevkon** [comment]
OK, there are many ways to do it. So you think adding `insertBefore/insertAfter` properties will just make the whole library more heavy and complicated?

**Comment by oyvindkinsey** [comment]
I'm generally a proponent of keeping libraries as slim as possible, and leave customization to the clients. In this case, the container support should give you 100% control of where the iframe is rendered (it's extremely rare that the extra wrapping div/span would be problematic - normally it's actually beneficial for styling purposes).

**Comment by oyvindkinsey** [comment]
Closing as a wont-fix given the discussion, and since the PR contains extra changes not discussed here.

**Pull request closed without merging**
